M48
; DRILL file KiCad 10.0.4 date 2026-07-10T16:40:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-10T16:40:35+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X94.5Y-30.0
X94.5Y-36.0
T2
X84.5Y-31.5
X84.5Y-79.0
X137.5Y-31.5
X138.0Y-79.0
M30
